openapi: 3.0.0
info:
  title: Studypot API
  description: 스터디그룹 관리 시스템 API 문서
  version: 1.0.0

servers:
  - url: http://localhost:3000
    description: Local server

paths:
  /auth/signup:
    post:
      summary: 회원가입
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserSignup"
      responses:
        "201":
          description: 회원가입 성공
        "400":
          description: 요청 형식 오류

  /auth/login:
    post:
      summary: 로그인
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserLogin"
      responses:
        "200":
          description: 로그인 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
        "401":
          description: 인증 실패

components:
  schemas:
    UserSignup:
      type: object
      required:
        - email
        - password
        - nickname
      properties:
        email:
          type: string
          example: test@example.com
        password:
          type: string
          example: securePassword123
        name:
          type: string
          example: studypotuser

    UserLogin:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          example: test@example.com
        password:
          type: string
          example: securePassword123
